SUBGRAPH_STUDIO_KEY: ""

UNISWAP_MAINNET_GAMMA_SUBGRAPH: 9paB7Eptzq98R9K7L5QQTixSxFLXuDzKwmSKkn8ddEWU
UNISWAP_MAINNET_HP_SUBGRAPH: https://api.thegraph.com/subgraphs/name/l0c4t0r/hype-pool-uniswap-mainnet
UNISWAP_MAINNET_SUBGRAPH: https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v3

UNISWAP_POLYGON_GAMMA_SUBGRAPH: https://api.thegraph.com/subgraphs/name/gammastrategies/polygon
UNISWAP_POLYGON_HP_SUBGRAPH: https://api.thegraph.com/subgraphs/name/l0c4t0r/hype-pool-uniswap-polygon
UNISWAP_POLYGON_SUBGRAPH: https://api.thegraph.com/subgraphs/name/ianlapham/uniswap-v3-polygon

UNISWAP_ARBITRUM_GAMMA_SUBGRAPH: https://api.thegraph.com/subgraphs/name/gammastrategies/arbitrum
UNISWAP_ARBITRUM_HP_SUBGRAPH: https://api.thegraph.com/subgraphs/name/l0c4t0r/hype-pool-uniswap-arbitrum
UNISWAP_ARBITRUM_SUBGRAPH: https://api.thegraph.com/subgraphs/name/ianlapham/arbitrum-dev

UNISWAP_OPTIMISM_GAMMA_SUBGRAPH: https://api.thegraph.com/subgraphs/name/gammastrategies/optimism
UNISWAP_OPTIMISM_HP_SUBGRAPH: https://api.thegraph.com/subgraphs/name/l0c4t0r/hype-pool-uniswap-optimism
UNISWAP_OPTIMISM_SUBGRAPH: https://api.thegraph.com/subgraphs/name/ianlapham/optimism-post-regenesis

UNISWAP_CELO_GAMMA_SUBGRAPH: https://api.thegraph.com/subgraphs/name/gammastrategies/celo
UNISWAP_CELO_HP_SUBGRAPH: https://api.thegraph.com/subgraphs/name/l0c4t0r/hype-pool-uniswap-celo
UNISWAP_CELO_SUBGRAPH: https://api.thegraph.com/subgraphs/name/jesse-sawa/uniswap-celo

UNISWAP_BSC_GAMMA_SUBGRAPH: https://api.thegraph.com/subgraphs/name/gammastrategies/uniswap-bsc
UNISWAP_BSC_HP_SUBGRAPH: https://api.thegraph.com/subgraphs/name/l0c4t0r/hype-pool-uniswap-bsc
UNISWAP_BSC_SUBGRAPH: https://api.thegraph.com/subgraphs/name/ianlapham/uniswap-v3-bsc

UNISWAP_MOONBEAM_GAMMA_SUBGRAPH: https://api.thegraph.com/subgraphs/name/l0c4t0r/gamma-moonbeam
UNISWAP_MOONBEAM_HP_SUBGRAPH: https://api.thegraph.com/subgraphs/name/l0c4t0r/hype-pool-uniswap-moonbeam
UNISWAP_MOONBEAM_SUBGRAPH: https://api.thegraph.com/subgraphs/name/ianlapham/uniswap-v3-moonbeam

UNISWAP_AVALANCHE_GAMMA_SUBGRAPH: https://api.studio.thegraph.com/query/44730/gamma-uniswap-avax/version/latest
UNISWAP_AVALANCHE_HP_SUBGRAPH: https://api.studio.thegraph.com/query/44730/gamma-hp-uniswap-avax/version/latest
UNISWAP_AVALANCHE_SUBGRAPH: _

UNISWAP_BASE_GAMMA_SUBGRAPH: https://api.studio.thegraph.com/query/44730/gamma-uniswap-base/version/latest
UNISWAP_BASE_HP_SUBGRAPH: https://api.studio.thegraph.com/query/44730/gamma-hp-uniswap-base/version/latest
UNISWAP_BASE_SUBGRAPH: _

UNISWAP_BLAST_GAMMA_SUBGRAPH: https://api.studio.thegraph.com/query/44730/gamma-uniswap-blast/version/latest
UNISWAP_BLAST_HP_SUBGRAPH: https://api.studio.thegraph.com/query/44730/gamma-hp-uniswap-blast/version/latest
UNISWAP_BLAST_SUBGRAPH: _

UNISWAP_SCROLL_GAMMA_SUBGRAPH: https://api.studio.thegraph.com/query/44730/gamma-uniswap-scroll/version/latest
UNISWAP_SCROLL_HP_SUBGRAPH: https://api.studio.thegraph.com/query/44730/gamma-hp-uniswap-scroll/version/latest
UNISWAP_SCROLL_SUBGRAPH: _

UNISWAP_LINEA_GAMMA_SUBGRAPH: https://api.studio.thegraph.com/query/44730/gamma-uniswap-linea/version/latest
UNISWAP_LINEA_HP_SUBGRAPH: https://api.studio.thegraph.com/query/44730/gamma-hp-uniswap-linea/version/latest
UNISWAP_LINEA_SUBGRAPH: _

UNISWAP_MANTLE_GAMMA_SUBGRAPH: https://subgraph-api.mantle.xyz/subgraphs/name/gamma-uniswap-mantle
UNISWAP_MANTLE_HP_SUBGRAPH: https://subgraph-api.mantle.xyz/subgraphs/name/gamma-hp-uniswap-mantle
UNISWAP_MANTLE_SUBGRAPH: _

UNISWAP_POLYGON_ZKEVM_GAMMA_SUBGRAPH: https://api.studio.thegraph.com/query/44730/gamma-uniswap-pzke/version/latest
UNISWAP_POLYGON_ZKEVM_HP_SUBGRAPH: https://api.studio.thegraph.com/query/44730/gamma-hp-uniswap-pzke/version/latest
UNISWAP_POLYGON_ZKEVM_SUBGRAPH: _

QUICKSWAP_POLYGON_GAMMA_SUBGRAPH: https://api.thegraph.com/subgraphs/name/gammastrategies/algebra-polygon
QUICKSWAP_POLYGON_HP_SUBGRAPH: https://api.thegraph.com/subgraphs/name/l0c4t0r/hype-pool-quickswap-polygon
QUICKSWAP_POLYGON_SUBGRAPH: https://api.thegraph.com/subgraphs/name/sameepsi/quickswap-v3

QUICKSWAP_POLYGON_ZKEVM_GAMMA_SUBGRAPH: https://api.studio.thegraph.com/query/44730/gamma-quickswap-pzke/version/latest
QUICKSWAP_POLYGON_ZKEVM_HP_SUBGRAPH: https://api.studio.thegraph.com/query/44730/gamma-hp-quickswap-pzke/version/latest
QUICKSWAP_POLYGON_ZKEVM_SUBGRAPH: https://api.studio.thegraph.com/query/44554/quickswap-v3-02/0.0.7

QUICKSWAP_MANTA_GAMMA_SUBGRAPH: https://api.goldsky.com/api/public/project_clols2c0p7fby2nww199i4pdx/subgraphs/gamma-quickswap-manta/latest/gn
QUICKSWAP_MANTA_HP_SUBGRAPH: https://api.goldsky.com/api/public/project_clols2c0p7fby2nww199i4pdx/subgraphs/gamma-hp-quickswap-manta/latest/gn
QUICKSWAP_MANTA_SUBGRAPH: _

QUICKSWAP_IMMUTABLE_ZKEVM_GAMMA_SUBGRAPH: https://api.goldsky.com/api/public/project_clols2c0p7fby2nww199i4pdx/subgraphs/gamma-quickswap-imtblzke/latest/gn
QUICKSWAP_IMMUTABLE_ZKEVM_HP_SUBGRAPH: https://api.goldsky.com/api/public/project_clols2c0p7fby2nww199i4pdx/subgraphs/gamma-hp-quickswap-imtblzke/latest/gn
QUICKSWAP_IMMUTABLE_ZKEVM_SUBGRAPH: _

QUICKSWAP_ASTAR_ZKEVM_GAMMA_SUBGRAPH: https://api.studio.thegraph.com/query/44730/gamma-quickswap-azke/version/latest
QUICKSWAP_ASTAR_ZKEVM_HP_SUBGRAPH: https://api.studio.thegraph.com/query/44730/gamma-hp-quickswap-azke/version/latest
QUICKSWAP_ASTAR_ZKEVM_SUBGRAPH: _

QUICKSWAP_UNISWAP_POLYGON_ZKEVM_GAMMA_SUBGRAPH: https://api.studio.thegraph.com/query/44730/gamma-quickswap-uni-pzke/version/latest
QUICKSWAP_UNISWAP_POLYGON_ZKEVM_HP_SUBGRAPH: https://api.studio.thegraph.com/query/44730/gamma-hp-quickswap-uni-pzke/version/latest
QUICKSWAP_UNISWAP_POLYGON_ZKEVM_SUBGRAPH: _

ZYBERSWAP_ARBITRUM_GAMMA_SUBGRAPH: https://api.thegraph.com/subgraphs/name/gammastrategies/zyberswap-arbitrum
ZYBERSWAP_ARBITRUM_HP_SUBGRAPH: https://api.thegraph.com/subgraphs/name/l0c4t0r/hype-pool-zyberswap-arbitrum
ZYBERSWAP_ARBITRUM_SUBGRAPH: https://api.thegraph.com/subgraphs/name/iliaazhel/zyberswap-info

THENA_BSC_GAMMA_SUBGRAPH: https://api.thegraph.com/subgraphs/name/gammastrategies/thena
THENA_BSC_HP_SUBGRAPH: https://api.thegraph.com/subgraphs/name/l0c4t0r/hype-pool-thena-bsc
THENA_BSC_SUBGRAPH: https://api.thegraph.com/subgraphs/name/iliaazhel/thena-info

THENA_OPBNB_GAMMA_SUBGRAPH: https://opbnb-mainnet-graph.nodereal.io/subgraphs/name/gamma-thena-opbnb
THENA_OPBNB_HP_SUBGRAPH: https://opbnb-mainnet-graph.nodereal.io/subgraphs/name/gamma-hp-thena-opbnb
THENA_OPBNB_SUBGRAPH: _

CAMELOT_ARBITRUM_GAMMA_SUBGRAPH: https://api.thegraph.com/subgraphs/name/l0c4t0r/gamma-camelot-arbitrum
CAMELOT_ARBITRUM_HP_SUBGRAPH: https://api.thegraph.com/subgraphs/name/l0c4t0r/hype-pool-camelot-arbitrum
CAMELOT_ARBITRUM_SUBGRAPH: https://api.thegraph.com/subgraphs/name/camelotlabs/camelot-amm-v3

GLACIER_AVALANCHE_GAMMA_SUBGRAPH: https://api.thegraph.com/subgraphs/name/l0c4t0r/gamma-glacier-avax
GLACIER_AVALANCHE_HP_SUBGRAPH: https://api.thegraph.com/subgraphs/name/l0c4t0r/hype-pool-glacier-avax
GLACIER_AVALANCHE_SUBGRAPH: https://api.thegraph.com/subgraphs/name/iliaazhel/glacier-info

RETRO_POLYGON_GAMMA_SUBGRAPH: https://api.thegraph.com/subgraphs/name/l0c4t0r/gamma-retro-polygon
RETRO_POLYGON_HP_SUBGRAPH: https://api.thegraph.com/subgraphs/name/l0c4t0r/hype-pool-retro-polygon
RETRO_POLYGON_SUBGRAPH: https://api.thegraph.com/subgraphs/name/ruvlol/univ3-test

STELLASWAP_MOONBEAM_GAMMA_SUBGRAPH: https://api.thegraph.com/subgraphs/name/l0c4t0r/gamma-stellaswap-moonbeam
STELLASWAP_MOONBEAM_HP_SUBGRAPH: https://api.thegraph.com/subgraphs/name/l0c4t0r/hype-pool-stellaswap-moonbeam
STELLASWAP_MOONBEAM_SUBGRAPH: https://api.thegraph.com/subgraphs/name/stellaswap/pulsar

BEAMSWAP_MOONBEAM_GAMMA_SUBGRAPH: https://api.thegraph.com/subgraphs/name/l0c4t0r/gamma-beamswap-moonbeam
BEAMSWAP_MOONBEAM_HP_SUBGRAPH: https://api.thegraph.com/subgraphs/name/l0c4t0r/hype-pool-beamswap-moonbeam
BEAMSWAP_MOONBEAM_SUBGRAPH: https://api.thegraph.com/subgraphs/name/rock-n-block/beamswap-v3-subgraph

SPIRITSWAP_FANTOM_GAMMA_SUBGRAPH: https://api.thegraph.com/subgraphs/name/l0c4t0r/gamma-spiritswap-fantom
SPIRITSWAP_FANTOM_HP_SUBGRAPH: https://api.thegraph.com/subgraphs/name/l0c4t0r/hype-pool-spiritswap-fantom
SPIRITSWAP_FANTOM_SUBGRAPH: https://api.thegraph.com/subgraphs/name/iliaazhel/spirit-info

SUSHI_POLYGON_GAMMA_SUBGRAPH: https://api.thegraph.com/subgraphs/name/l0c4t0r/gamma-sushi-polygon
SUSHI_POLYGON_HP_SUBGRAPH: https://api.thegraph.com/subgraphs/name/l0c4t0r/hype-pool-sushi-polygon
SUSHI_POLYGON_SUBGRAPH: https://api.thegraph.com/subgraphs/name/sushi-v3/v3-polygon

SUSHI_ARBITRUM_GAMMA_SUBGRAPH: https://api.thegraph.com/subgraphs/name/l0c4t0r/gamma-sushi-arbitrum
SUSHI_ARBITRUM_HP_SUBGRAPH: https://api.thegraph.com/subgraphs/name/l0c4t0r/hype-pool-sushi-arbitrum
SUSHI_ARBITRUM_SUBGRAPH: https://api.thegraph.com/subgraphs/name/sushi-v3/v3-arbitrum

SUSHI_BASE_GAMMA_SUBGRAPH: https://api.thegraph.com/subgraphs/name/l0c4t0r/gamma-sushi-base
SUSHI_BASE_HP_SUBGRAPH: https://api.thegraph.com/subgraphs/name/l0c4t0r/hype-pool-sushi-base
SUSHI_BASE_SUBGRAPH: https://api.studio.thegraph.com/query/32073/v3-base/version/latest

RAMSES_ARBITRUM_GAMMA_SUBGRAPH: https://api.thegraph.com/subgraphs/name/l0c4t0r/gamma-ramses-arbitrum
RAMSES_ARBITRUM_HP_SUBGRAPH: https://api.thegraph.com/subgraphs/name/l0c4t0r/hype-pool-ramses-arbitrum
RAMSES_ARBITRUM_SUBGRAPH: https://api.thegraph.com/subgraphs/name/ramsesexchange/concentrated-liquidity-graph

NILE_LINEA_GAMMA_SUBGRAPH: https://api.studio.thegraph.com/query/44730/gamma-nile-linea/version/latest
NILE_LINEA_HP_SUBGRAPH: https://api.studio.thegraph.com/query/44730/gamma-hp-nile-linea/version/latest
NILE_LINEA_SUBGRAPH: _

ASCENT_POLYGON_GAMMA_SUBGRAPH: https://api.thegraph.com/subgraphs/name/l0c4t0r/gamma-ascent-polygon
ASCENT_POLYGON_HP_SUBGRAPH: https://api.thegraph.com/subgraphs/name/l0c4t0r/hype-pool-ascent-polygon
ASCENT_POLYGON_SUBGRAPH: https://api.thegraph.com/subgraphs/name/seme0801/ascent-v3

FUSIONX_MANTLE_GAMMA_SUBGRAPH: https://graphv3.fusionx.finance/subgraphs/name/gamma-fusionx-mantle
FUSIONX_MANTLE_HP_SUBGRAPH: https://graphv3.fusionx.finance/subgraphs/name/gamma-hp-fusionx-mantle
FUSIONX_MANTLE_SUBGRAPH: https://graphv3.fusionx.finance/subgraphs/name/fusionx/exchange-v3

SYNTHSWAP_BASE_GAMMA_SUBGRAPH: https://api.thegraph.com/subgraphs/name/l0c4t0r/gamma-synthswap-base
SYNTHSWAP_BASE_HP_SUBGRAPH: https://api.thegraph.com/subgraphs/name/l0c4t0r/hype-pool-synthswap-base
SYNTHSWAP_BASE_SUBGRAPH: https://api.studio.thegraph.com/query/45189/synthswap-v3-analytics-base/version/latest/

LYNEX_LINEA_GAMMA_SUBGRAPH: https://api.studio.thegraph.com/query/44730/gamma-lynex-linea/version/latest
LYNEX_LINEA_HP_SUBGRAPH: https://api.studio.thegraph.com/query/44730/gamma-hp-lynex-linea/version/latest
LYNEX_LINEA_SUBGRAPH: https://graph-query.linea.build/subgraphs/name/cryptoalgebra/analytics

PEGASYS_ROLLUX_GAMMA_SUBGRAPH: https://rollux.graph.pegasys.fi/subgraphs/name/gammastrategies/pegasys-rollux
PEGASYS_ROLLUX_HP_SUBGRAPH: https://rollux.graph.pegasys.fi/subgraphs/name/gammastrategies/hype-pool-pegasys-rollux
PEGASYS_ROLLUX_SUBGRAPH: https://rollux.graph.pegasys.fi/subgraphs/name/pollum-io/pegasys-v3

BASEX_BASE_GAMMA_SUBGRAPH: https://api.thegraph.com/subgraphs/name/l0c4t0r/gamma-basex-base
BASEX_BASE_HP_SUBGRAPH: https://api.thegraph.com/subgraphs/name/l0c4t0r/hype-pool-basex-base
BASEX_BASE_SUBGRAPH: https://api.thegraph.com/subgraphs/name/basex/base

PANCAKESWAP_ARBITRUM_GAMMA_SUBGRAPH: https://api.thegraph.com/subgraphs/name/l0c4t0r/gamma-pancakeswap-arbitrum
PANCAKESWAP_ARBITRUM_HP_SUBGRAPH: https://api.thegraph.com/subgraphs/name/l0c4t0r/hype-pool-pancakeswap-arbitrum
PANCAKESWAP_ARBITRUM_SUBGRAPH: https://api.thegraph.com/subgraphs/name/pancakeswap/exchange-v3-arb

APERTURE_MANTA_GAMMA_SUBGRAPH: https://api.goldsky.com/api/public/project_clols2c0p7fby2nww199i4pdx/subgraphs/gamma-aperture-manta/latest/gn
APERTURE_MANTA_HP_SUBGRAPH: https://api.goldsky.com/api/public/project_clols2c0p7fby2nww199i4pdx/subgraphs/gamma-hp-aperture-manta/latest/gn
APERTURE_MANTA_SUBGRAPH: https://api.goldsky.com/api/public/project_clnz7akg41cv72ntv0uhyd3ai/subgraphs/aperture/uniswap-v3/gn

HERCULES_METIS_GAMMA_SUBGRAPH: https://metisapi.0xgraph.xyz/subgraphs/name/gamma-hercules-metis
HERCULES_METIS_HP_SUBGRAPH: https://metisapi.0xgraph.xyz/subgraphs/name/gamma-hp-hercules-metis
HERCULES_METIS_SUBGRAPH: _

BASESWAP_BASE_GAMMA_SUBGRAPH: https://api.studio.thegraph.com/query/44730/gamma-baseswap-base/version/latest
BASESWAP_BASE_HP_SUBGRAPH: https://api.studio.thegraph.com/query/44730/gamma-hp-baseswap-base/version/latest
BASESWAP_BASE_SUBGRAPH: _

SWAPBASED_BASE_GAMMA_SUBGRAPH: https://api.studio.thegraph.com/query/44730/gamma-swapbased-base/version/latest
SWAPBASED_BASE_HP_SUBGRAPH: https://api.studio.thegraph.com/query/44730/gamma-hp-swapbased-base/version/latest
SWAPBASED_BASE_SUBGRAPH: _

PHARAOH_AVALANCHE_GAMMA_SUBGRAPH: https://api.thegraph.com/subgraphs/name/l0c4t0r/gamma-pharaoh-avax
PHARAOH_AVALANCHE_HP_SUBGRAPH: https://api.thegraph.com/subgraphs/name/l0c4t0r/gamma-hp-pharaoh-avax
PHARAOH_AVALANCHE_SUBGRAPH: _

SWAPR_GNOSIS_GAMMA_SUBGRAPH: https://api.thegraph.com/subgraphs/name/l0c4t0r/gamma-swapr-gnosis
SWAPR_GNOSIS_HP_SUBGRAPH: https://api.thegraph.com/subgraphs/name/l0c4t0r/gamma-hp-swapr-gnosis
SWAPR_GNOSIS_SUBGRAPH: _

THICK_BASE_GAMMA_SUBGRAPH: https://api.studio.thegraph.com/query/44730/gamma-thick-base/version/latest
THICK_BASE_HP_SUBGRAPH: https://api.studio.thegraph.com/query/44730/gamma-hp-thick-base/version/latest
THICK_BASE_SUBGRAPH: _

CLEOPATRA_MANTLE_GAMMA_SUBGRAPH: https://subgraph-api.mantle.xyz/subgraphs/name/gamma-cleopatra-mantle
CLEOPATRA_MANTLE_HP_SUBGRAPH: https://subgraph-api.mantle.xyz/subgraphs/name/gamma-hp-cleopatra-mantle
CLEOPATRA_MANTLE_SUBGRAPH: _

BLASTER_BLAST_GAMMA_SUBGRAPH: https://api.studio.thegraph.com/query/44730/gamma-blaster-blast/version/latest
BLASTER_BLAST_HP_SUBGRAPH: https://api.studio.thegraph.com/query/44730/gamma-hp-blaster-blast/version/latest
BLASTER_BLAST_SUBGRAPH: _

THRUSTER_BLAST_GAMMA_SUBGRAPH: https://api.studio.thegraph.com/query/44730/gamma-thruster-blast/version/latest
THRUSTER_BLAST_HP_SUBGRAPH: https://api.studio.thegraph.com/query/44730/gamma-hp-thruster-blast/version/latest
THRUSTER_BLAST_SUBGRAPH: _

FENIX_BLAST_GAMMA_SUBGRAPH: https://api.studio.thegraph.com/query/73506/gamma-fenix-blast/version/latest
FENIX_BLAST_HP_SUBGRAPH: https://api.studio.thegraph.com/query/73506/gamma-hp-fenix-blast/version/latest
FENIX_BLAST_SUBGRAPH: _

QUICKSWAP_XLAYER_GAMMA_SUBGRAPH: https://api.studio.thegraph.com/query/73506/gamma-quickswap-xlayer/version/latest
QUICKSWAP_XLAYER_HP_SUBGRAPH: https://api.studio.thegraph.com/query/73506/gamma-hp-quickswap-xlayer/version/latest
QUICKSWAP_XLAYER_SUBGRAPH: _

XTRADE_XLAYER_GAMMA_SUBGRAPH: https://api.studio.thegraph.com/query/73506/gamma-xtrade-xlayer/version/latest
XTRADE_XLAYER_HP_SUBGRAPH: https://api.studio.thegraph.com/query/73506/gamma-hp-xtrade-xlayer/version/latest
XTRADE_XLAYER_SUBGRAPH: _

# Masterchef addresses
MASTERCHEF_ADDRESSES: {
  "ethereum":{},
  "polygon": {
    "uniswap":["0x570d60a60baa356d47fda3017a190a48537fcd7d"],
  },
  "arbitrum":{},
  "optimism":{
    "uniswap":["0xc7846d1bc4d8bcf7c45a7c998b77ce9b3c904365"], 
    "quickswap":["0x20ec0d06f447d550fc6edee42121bc8c1817b97d","0x68678cf174695fc2d27bd312df67a3984364ffdd"]}, 
  "celo":{},
  "bsc":{},
}


# Timezone for daily data
TIMEZONE: UTC-5

# Cache timeout settings
CHARTS_CACHE_TIMEOUT: 600
APY_CACHE_TIMEOUT: 600
DASHBOARD_CACHE_TIMEOUT: 600
ALLDATA_CACHE_TIMEOUT: 600
DB_CACHE_TIMEOUT: 160
DAILY_CACHE_TIMEOUT: 7200 # 2hours
LONG_CACHE_TIMEOUT: 345600 # 4day

# Set timeout for GQL queries
GQL_CLIENT_TIMEOUT: 120

# Comma delimited list of hypes to exclude
EXCLUDED_HYPES: ""

# MongoDB settings
MONGO_DB_URL: mongodb://localhost:27072
MONGO_DB_TIMEOUTMS: 2000

RUN_FIRST_QUERY_TYPE: subgraph # database


# Web3 config

WEB3_PROVIDER_URLS:
  public: 
    ethereum:
      - "https://cloudflare-eth.com"
      - "https://ethereum.publicnode.com"
      - "https://ethereum-mainnet-archive.allthatnode.com"
      - "https://1rpc.io/eth"
      - "https://api.securerpc.com/v1"
    optimism:
      - "https://mainnet.optimism.io/"
      - "https://1rpc.io/op"
      - "https://endpoints.omniatech.io/v1/op/mainnet/public"
    arbitrum:
      - "https://arb1.arbitrum.io/rpc"
      - "https://rpc.ankr.com/arbitrum"
      - "https://arbitrum.blockpi.network/v1/rpc/public"
    polygon:
      - "https://polygon-rpc.com/"
      - "https://rpc-mainnet.matic.network"
      - "https://matic-mainnet.chainstacklabs.com"
      - "https://rpc-mainnet.maticvigil.com"
      - "https://rpc-mainnet.matic.quiknode.pro"
      - "https://matic-mainnet-full-rpc.bwarelabs.com"
      - "https://polygon-bor.publicnode.com"
    polygon_zkevm:
      - "https://rpc.polygon-zkevm.gateway.fm"
      - "https://zkevm-rpc.com"
      - "https://rpc.ankr.com/polygon_zkevm"
    bsc:
      - "https://bsc-dataseed1.binance.org"
      - "https://bsc-dataseed2.binance.org"
      - "https://bsc-dataseed3.binance.org"
      - "https://bsc-dataseed4.binance.org"
      - "https://bsc-dataseed1.defibit.io"
      - "https://bsc-dataseed2.defibit.io"
      - "https://bsc-dataseed3.defibit.io"
      - "https://bsc-dataseed4.defibit.io"
      - "https://bsc-dataseed1.ninicoin.io"
      - "https://bsc-dataseed2.ninicoin.io"
      - "https://bsc-dataseed3.ninicoin.io"
      - "https://bsc-dataseed4.ninicoin.io"
      - "https://bsc.publicnode.com"
      - "https://bsc.rpc.blxrbdn.com"
    avalanche:
      - "https://api.avax.network/ext/bc/C/rpc"
      - "https://rpc.ankr.com/avalanche"
      - "https://avalanche.api.onfinality.io/public/ext/bc/P"
      - "https://avalanche-c-chain.publicnode.com"
      - "https://avalanche.blockpi.network/v1/rpc/public"
    celo:
      - "https://forno.celo.org"
      - "https://rpc.ankr.com/celo"
      - "https://1rpc.io/celo"
  private:

WEB3_PROVIDER_DEFAULT_ORDER: ["public", "private"]

