# GAMMA Subgraph URL
UNISWAP_MAINNET_GAMMA_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/gammastrategies/gamma
UNISWAP_POLYGON_GAMMA_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/gammastrategies/polygon
UNISWAP_ARBITRUM_GAMMA_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/gammastrategies/arbitrum
UNISWAP_OPTIMISM_GAMMA_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/gammastrategies/optimism
UNISWAP_CELO_GAMMA_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/gammastrategies/celo
UNISWAP_BSC_GAMMA_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/gammastrategies/uniswap-bsc
QUICKSWAP_POLYGON_GAMMA_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/gammastrategies/algebra-polygon
QUICKSWAP_POLYGON_ZKEVM_GAMMA_SUBGRAPH_URL: https://api.studio.thegraph.com/query/44730/gamma-quickswap-pzke/version/latest
ZYBERSWAP_ARBITRUM_GAMMA_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/gammastrategies/zyberswap-arbitrum
THENA_BSC_GAMMA_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/gammastrategies/thena
CAMELOT_ARBITRUM_GAMMA_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/l0c4t0r/gamma-camelot-arbitrum
GLACIER_AVALANCHE_GAMMA_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/l0c4t0r/gamma-glacier-avax
RETRO_POLYGON_GAMMA_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/l0c4t0r/gamma-retro-polygon
STELLASWAP_MOONBEAM_GAMMA_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/l0c4t0r/gamma-stellaswap-moonbeam
BEAMSWAP_MOONBEAM_GAMMA_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/l0c4t0r/gamma-beamswap-moonbeam
SPIRITSWAP_FANTOM_GAMMA_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/l0c4t0r/gamma-spiritswap-fantom
SUSHI_POLYGON_GAMMA_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/l0c4t0r/gamma-sushi-polygon
SUSHI_ARBITRUM_GAMMA_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/l0c4t0r/gamma-sushi-arbitrum
RAMSES_ARBITRUM_GAMMA_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/l0c4t0r/gamma-ramses-arbitrum
ASCENT_POLYGON_GAMMA_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/l0c4t0r/gamma-ascent-polygon

# DEX Subgraph URL
UNISWAP_MAINNET_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v3
UNISWAP_POLYGON_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/ianlapham/uniswap-v3-polygon
UNISWAP_ARBITRUM_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/ianlapham/arbitrum-dev
UNISWAP_OPTIMISM_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/ianlapham/optimism-post-regenesis
UNISWAP_CELO_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/jesse-sawa/uniswap-celo
UNISWAP_BSC_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/ianlapham/uniswap-v3-bsc
QUICKSWAP_POLYGON_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/sameepsi/quickswap-v3
QUICKSWAP_POLYGON_ZKEVM_SUBGRAPH_URL: https://api.studio.thegraph.com/query/44554/quickswap-v3-02/0.0.7
ZYBERSWAP_ARBITRUM_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/iliaazhel/zyberswap-info
THENA_BSC_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/iliaazhel/thena-info
CAMELOT_ARBITRUM_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/camelotlabs/camelot-amm-v3
GLACIER_AVALANCHE_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/iliaazhel/glacier-info
RETRO_POLYGON_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/ruvlol/univ3-test
STELLASWAP_MOONBEAM_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/stellaswap/pulsar
BEAMSWAP_MOONBEAM_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/rock-n-block/beamswap-v3-subgraph
SPIRITSWAP_FANTOM_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/iliaazhel/spirit-info
SUSHI_POLYGON_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/sushi-v3/v3-polygon
SUSHI_ARBITRUM_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/sushi-v3/v3-arbitrum
RAMSES_ARBITRUM_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/ramsesexchange/concentrated-liquidity-graph
ASCENT_POLYGON_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/seme0801/ascent-subgraph2

# HypePool Subgraph URL
UNISWAP_MAINNET_HP_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/l0c4t0r/hype-pool-uniswap-mainnet
UNISWAP_POLYGON_HP_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/l0c4t0r/hype-pool-uniswap-polygon
UNISWAP_ARBITRUM_HP_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/l0c4t0r/hype-pool-uniswap-arbitrum
UNISWAP_OPTIMISM_HP_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/l0c4t0r/hype-pool-uniswap-optimism
UNISWAP_CELO_HP_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/l0c4t0r/hype-pool-uniswap-celo
UNISWAP_BSC_HP_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/l0c4t0r/hype-pool-uniswap-bsc
QUICKSWAP_POLYGON_HP_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/l0c4t0r/hype-pool-quickswap-polygon
QUICKSWAP_POLYGON_ZKEVM_HP_SUBGRAPH_URL: https://api.studio.thegraph.com/query/44730/gamma-hp-quickswap-pzke/version/latest
ZYBERSWAP_ARBITRUM_HP_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/l0c4t0r/hype-pool-zyberswap-arbitrum
THENA_BSC_HP_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/l0c4t0r/hype-pool-thena-bsc
CAMELOT_ARBITRUM_HP_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/l0c4t0r/hype-pool-camelot-arbitrum
GLACIER_AVALANCHE_HP_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/l0c4t0r/hype-pool-glacier-avax
RETRO_POLYGON_HP_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/l0c4t0r/hype-pool-retro-polygon
STELLASWAP_MOONBEAM_HP_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/l0c4t0r/hype-pool-stellaswap-moonbeam
BEAMSWAP_MOONBEAM_HP_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/l0c4t0r/hype-pool-beamswap-moonbeam
SPIRITSWAP_FANTOM_HP_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/l0c4t0r/hype-pool-spiritswap-fantom
SUSHI_POLYGON_HP_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/l0c4t0r/hype-pool-sushi-polygon
SUSHI_ARBITRUM_HP_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/l0c4t0r/hype-pool-sushi-arbitrum
RAMSES_ARBITRUM_HP_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/l0c4t0r/hype-pool-ramses-arbitrum
ASCENT_POLYGON_HP_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/l0c4t0r/hype-pool-ascent-polygon

# Masterchef addresses
MASTERCHEF_ADDRESSES: {
  "ethereum":{},
  "polygon": {
    "uniswap":["0x570d60a60baa356d47fda3017a190a48537fcd7d"],
  },
  "arbitrum":{},
  "optimism":{
    "uniswap":["0xc7846d1bc4d8bcf7c45a7c998b77ce9b3c904365"], 
    "quickswap":["0x20ec0d06f447d550fc6edee42121bc8c1817b97d","0x68678cf174695fc2d27bd312df67a3984364ffdd"]}, 
  "celo":{},
  "bsc":{},
}


# Timezone for daily data
TIMEZONE: UTC-5

# Cache timeout settings
CHARTS_CACHE_TIMEOUT: 600
APY_CACHE_TIMEOUT: 600
DASHBOARD_CACHE_TIMEOUT: 600
ALLDATA_CACHE_TIMEOUT: 600
DB_CACHE_TIMEOUT: 160

# Set timeout for GQL queries
GQL_CLIENT_TIMEOUT: 120

# Comma delimited list of hypes to exclude
EXCLUDED_HYPES: ""

# MongoDB settings
MONGO_DB_URL: mongodb://localhost:27072
MONGO_DB_TIMEOUTMS: 2000

RUN_FIRST_QUERY_TYPE: subgraph # database


# Web3 config

WEB3_PROVIDER_URLS:
  public: 
    ethereum:
      - "https://cloudflare-eth.com"
      - "https://ethereum.publicnode.com"
      - "https://ethereum-mainnet-archive.allthatnode.com"
      - "https://1rpc.io/eth"
      - "https://api.securerpc.com/v1"
    optimism:
      - "https://mainnet.optimism.io/"
      - "https://1rpc.io/op"
      - "https://endpoints.omniatech.io/v1/op/mainnet/public"
    arbitrum:
      - "https://arb1.arbitrum.io/rpc"
      - "https://rpc.ankr.com/arbitrum"
      - "https://arbitrum.blockpi.network/v1/rpc/public"
    polygon:
      - "https://polygon-rpc.com/"
      - "https://rpc-mainnet.matic.network"
      - "https://matic-mainnet.chainstacklabs.com"
      - "https://rpc-mainnet.maticvigil.com"
      - "https://rpc-mainnet.matic.quiknode.pro"
      - "https://matic-mainnet-full-rpc.bwarelabs.com"
      - "https://polygon-bor.publicnode.com"
    polygon_zkevm:
      - "https://rpc.polygon-zkevm.gateway.fm"
      - "https://zkevm-rpc.com"
      - "https://rpc.ankr.com/polygon_zkevm"
    bsc:
      - "https://bsc-dataseed1.binance.org"
      - "https://bsc-dataseed2.binance.org"
      - "https://bsc-dataseed3.binance.org"
      - "https://bsc-dataseed4.binance.org"
      - "https://bsc-dataseed1.defibit.io"
      - "https://bsc-dataseed2.defibit.io"
      - "https://bsc-dataseed3.defibit.io"
      - "https://bsc-dataseed4.defibit.io"
      - "https://bsc-dataseed1.ninicoin.io"
      - "https://bsc-dataseed2.ninicoin.io"
      - "https://bsc-dataseed3.ninicoin.io"
      - "https://bsc-dataseed4.ninicoin.io"
      - "https://bsc.publicnode.com"
      - "https://bsc.rpc.blxrbdn.com"
    avalanche:
      - "https://api.avax.network/ext/bc/C/rpc"
      - "https://rpc.ankr.com/avalanche"
      - "https://avalanche.api.onfinality.io/public/ext/bc/P"
      - "https://avalanche-c-chain.publicnode.com"
      - "https://avalanche.blockpi.network/v1/rpc/public"
    celo:
      - "https://forno.celo.org"
      - "https://rpc.ankr.com/celo"
      - "https://1rpc.io/celo"
  private:

WEB3_PROVIDER_DEFAULT_ORDER: ["public", "private"]

